# Site Settings
title: LUG | Student Blog
email: a.lartey@student.lancaster.edu.gh
description: Lancaster University Ghana is the centre for excellent student experience! The voices of the students matter as our campus has quickly become the preferred destination for students across the continent. The purpose of this website is to equip present and potential students with essential information about food, accommodation, activities and student representation. What you will discover from this blog is that we have a unique mix of student leaders who- like you- want the best out of their student experience at Lancaster University Ghana. 
baseurl: "/lugstudentblog" # the subpath of your site, e.g. /blog
url: "https://www.lancaster.edu.gh" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: LUG | Student Blog
user_description: Some text about you.
disqus_username: brainiqslab

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Featured Students
    url: /featuredstudents/
  - title: Students Council
    url: /studentcouncil/
  - title: Clubs & Societies
    url: /clubsocieties/
  - title: Academic Support
    url: /academicsupport/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
